<?php

namespace YoVideo;

class Country{

	private $data = [];

	public function  __construct(){
		$this->setData();
	}

	public function setData(){
		$this->data = [
			['code' => 'af', 'locale' => 'af_AF', 'name' => 'Afghanistan',					'language' => 'Dari',					'nationality' => 'Afghane'],
			['code' => 'za', 'locale' => 'za_ZA', 'name' => 'Afrique du Sud',				'language' => 'Zoulou',					'nationality' => 'Sud-Africaine'],
			['code' => 'al', 'locale' => 'al_AL', 'name' => 'Albanie',						'language' => 'Albanais',				'nationality' => 'Albanaise'],
			['code' => 'dz', 'locale' => 'dz_DZ', 'name' => 'Algerie',						'language' => 'Arabe',					'nationality' => 'Algérienne'],
			['code' => 'de', 'locale' => 'de_DE', 'name' => 'Allemagne',					'language' => 'Allemand',				'nationality' => 'Allemande'],
			['code' => 'ad', 'locale' => 'ad_AD', 'name' => 'Andorre',						'language' => 'Catalan',				'nationality' => 'Andorrane'],
			['code' => 'gb', 'locale' => 'gb_GB', 'name' => 'Angleterre',					'language' => 'Anglais',				'nationality' => 'Anglaise'],
			['code' => 'ao', 'locale' => 'ao_AO', 'name' => 'Angola',						'language' => 'Portugais',				'nationality' => 'Angolaise'],
			['code' => 'ac', 'locale' => 'ac_AC', 'name' => 'Antigua-et-Barbuda',			'language' => 'Anglais',				'nationality' => 'Antiguaise'],
			['code' => 'sa', 'locale' => 'sa_SA', 'name' => 'Arabie Saoudite',				'language' => 'Arabe',					'nationality' => 'Saoudienne'],
			['code' => 'ar', 'locale' => 'ar_AR', 'name' => 'Argentine',					'language' => 'Espagnol',				'nationality' => 'Argentine'],
			['code' => 'am', 'locale' => 'am_AM', 'name' => 'Armenie',						'language' => 'Arménien',				'nationality' => 'Arménienne'],
			['code' => 'au', 'locale' => 'au_AU', 'name' => 'Australie',					'language' => 'Anglais',				'nationality' => 'Australienne'],
			['code' => 'at', 'locale' => 'at_AT', 'name' => 'Autriche',						'language' => 'Allemand',				'nationality' => 'Autrichienne'],
			['code' => 'az', 'locale' => 'az_AZ', 'name' => 'Azerbaidjan',					'language' => 'Azéri',					'nationality' => 'Azerbaidjanaise'],
			['code' => 'bs', 'locale' => 'bs_BS', 'name' => 'Bahamas',						'language' => 'Anglais',				'nationality' => 'Bahaméenne'],
			['code' => 'bh', 'locale' => 'bh_BH', 'name' => 'Bahrain',						'language' => 'Arabe',					'nationality' => 'Bahreïnienne'],
			['code' => 'bd', 'locale' => 'bd_BD', 'name' => 'Bangladesh',					'language' => 'Bengali',				'nationality' => 'Bangladeshie'],
			['code' => 'bb', 'locale' => 'bb_BB', 'name' => 'Barbades',						'language' => 'Anglais',				'nationality' => 'Barbadienne'],
			['code' => 'be', 'locale' => 'be_BE', 'name' => 'Belgique',						'language' => 'Français',				'nationality' => 'Belge'],
			['code' => 'bz', 'locale' => 'bz_BZ', 'name' => 'Belize',						'language' => 'Anglais',				'nationality' => 'Belizienne'],
			['code' => 'bj', 'locale' => 'bj_BJ', 'name' => 'Benin',						'language' => 'Français',				'nationality' => 'Béninoise'],
			['code' => 'bm', 'locale' => 'bm_BM', 'name' => 'Bermudes',						'language' => 'Anglais',				'nationality' => 'Bermudienne'],
			['code' => 'by', 'locale' => 'by_BY', 'name' => 'Biélorussie',					'language' => 'Russe',					'nationality' => 'Biélorusse'],
			['code' => 'bo', 'locale' => 'bo_BO', 'name' => 'Bolivie',						'language' => 'Aymara',					'nationality' => 'Bolivienne'],
			['code' => 'ba', 'locale' => 'ba_BA', 'name' => 'Bosnie Herzegovine',			'language' => 'Bosnien',				'nationality' => 'Bosnienne'],
			['code' => 'bw', 'locale' => 'bw_BW', 'name' => 'Botswana',						'language' => 'Tswana',					'nationality' => 'Botswanaise'],
			['code' => 'bt', 'locale' => 'bt_BT', 'name' => 'Boutan',						'language' => 'Dzongkha',				'nationality' => 'Bhoutanaise'],
			['code' => 'br', 'locale' => 'br_BR', 'name' => 'Brésil',						'language' => 'Portugais',				'nationality' => 'Brésilienne'],
			['code' => 'bg', 'locale' => 'bg_BG', 'name' => 'Bulgarie',						'language' => 'Bulgare',				'nationality' => 'Bulgare'],
			['code' => 'bf', 'locale' => 'bf_BF', 'name' => 'Burkina Faso',					'language' => 'Français',				'nationality' => 'Burkinabé'],
			['code' => 'bi', 'locale' => 'bi_BI', 'name' => 'Burundi',						'language' => 'Kirundi',				'nationality' => 'Burundaise'],
			['code' => 'kh', 'locale' => 'kh_KH', 'name' => 'Cambodge',						'language' => 'Khmer',					'nationality' => 'Cambodgienne'],		
			['code' => 'cm', 'locale' => 'cm_CM', 'name' => 'Cameroun', 					'language' => 'Français',				'nationality' => 'Camerounaise'],
			['code' => 'ca', 'locale' => 'ca_CA', 'name' => 'Canada', 						'language' => 'Anglais',				'nationality' => 'Canadienne'],
			['code' => 'cv', 'locale' => 'cv_CV', 'name' => 'Cap Vert', 					'language' => 'Portugais',				'nationality' => 'Capverdienne'],
			['code' => 'cl', 'locale' => 'cl_CL', 'name' => 'Chilie', 						'language' => 'Espagnol',				'nationality' => 'Chilienne'],
			['code' => 'cn', 'locale' => 'cn_CN', 'name' => 'Chine', 						'language' => 'Mandarin',				'nationality' => 'Chinoise'],
			['code' => 'cy', 'locale' => 'cy_CY', 'name' => 'Chypre', 						'language' => 'Grec',					'nationality' => 'Chypriote'],
			['code' => 'co', 'locale' => 'co_CO', 'name' => 'Colombie', 					'language' => 'Espagnol',				'nationality' => 'Colombienne'],
			['code' => 'kp', 'locale' => 'kp_KP', 'name' => 'Corée du Nord', 				'language' => 'Coréen',					'nationality' => 'Nord-Coréenne'],
			['code' => 'kr', 'locale' => 'kr_KR', 'name' => 'Corée du Sud', 				'language' => 'Coréen',					'nationality' => 'Sud-Coréenne'],
			['code' => 'cr', 'locale' => 'cr_CR', 'name' => 'Costa Rica', 					'language' => 'Espagnol',				'nationality' => 'Costaricienne'],
			['code' => 'ci', 'locale' => 'ci_CI', 'name' => 'Côte d\'Ivoire', 				'language' => 'Français',				'nationality' => 'Ivoirienne'],
			['code' => 'hr', 'locale' => 'hr_HR', 'name' => 'Croatie', 						'language' => 'Croate',					'nationality' => 'Croate'],
			['code' => 'cu', 'locale' => 'cu_CU', 'name' => 'Cuba', 						'language' => 'Espagnol',				'nationality' => 'Cubaine'],
			['code' => 'dk', 'locale' => 'dk_DK', 'name' => 'Danemark', 					'language' => 'Danois',					'nationality' => 'Danoise'],
			['code' => 'dj', 'locale' => 'dj_DJ', 'name' => 'Djibouti', 					'language' => 'Arabe',					'nationality' => 'Djiboutienne'],
			['code' => 'eg', 'locale' => 'eg_EG', 'name' => 'Egypte', 						'language' => 'Arabe',					'nationality' => 'Egyptienne'],
			['code' => 'tc', 'locale' => 'tc_TC', 'name' => 'Émirats Arabes Unis',			'language' => 'Arabe',					'nationality' => 'Emirienne'],
			['code' => 'ec', 'locale' => 'ec_EC', 'name' => 'Equateur',						'language' => 'Espagnol',				'nationality' => 'Equatorienne'],
			['code' => 'sp', 'locale' => 'sp_SP', 'name' => 'Espagne',						'language' => 'Espagnol',				'nationality' => 'Espagnole'],
			['code' => 'ee', 'locale' => 'ee_EE', 'name' => 'Estonie',						'language' => 'Estonien',				'nationality' => 'Estonienne'],
			['code' => 'et', 'locale' => 'et_ET', 'name' => 'Ethiopie',						'language' => 'Amharique',				'nationality' => 'Ethiopienne'],
			['code' => 'fi', 'locale' => 'fi_FI', 'name' => 'Finlande',						'language' => 'Finnois',				'nationality' => 'Finlandaise'],
			['code' => 'fr', 'locale' => 'fr_FR', 'name' => 'France',						'language' => 'Français',				'nationality' => 'Française'],
			['code' => 'ga', 'locale' => 'ga_GA', 'name' => 'Gabon',						'language' => 'Français',				'nationality' => 'Gabonaise'],
			['code' => 'ge', 'locale' => 'ge_GE', 'name' => 'Georgie',						'language' => 'Géorgien',				'nationality' => 'Géorgienne'],
			['code' => 'gh', 'locale' => 'gh_GH', 'name' => 'Ghana',						'language' => 'Anglais',				'nationality' => 'Ghanéenne'],
			['code' => 'gi', 'locale' => 'gi_GI', 'name' => 'Gibraltar',					'language' => 'Anglais',				'nationality' => 'Gibraltarienne'],
			['code' => 'gr', 'locale' => 'gr_GR', 'name' => 'Grèce',						'language' => 'Grec',					'nationality' => 'Grecque'],
			['code' => 'gd', 'locale' => 'gd_GD', 'name' => 'Grenade',						'language' => 'Anglais',				'nationality' => 'Grenadienne'],
			['code' => 'gu', 'locale' => 'gu_GU', 'name' => 'Guam',							'language' => 'Anglais',				'nationality' => 'Américaine'],
			['code' => 'gt', 'locale' => 'gt_GT', 'name' => 'Guatemala',					'language' => 'Espagnol',				'nationality' => 'Guatémaltèque'],
			['code' => 'gn', 'locale' => 'gn_GN', 'name' => 'Guinée',						'language' => 'Français',				'nationality' => 'Guinéenne'],
			['code' => 'ht', 'locale' => 'ht_HT', 'name' => 'Haiti',						'language' => 'Créole',					'nationality' => 'Haitienne'],
			['code' => 'hn', 'locale' => 'hn_HN', 'name' => 'Honduras',						'language' => 'Espagnol',				'nationality' => 'Hondurienne'],
			['code' => 'hk', 'locale' => 'hk_HK', 'name' => 'Hong Kong',					'language' => 'Cantonais',				'nationality' => 'Hongkongaise'],
			['code' => 'hu', 'locale' => 'hu_HU', 'name' => 'Hongrie',						'language' => 'Hongrois',				'nationality' => 'Hongroise'],
			['code' => 'ic', 'locale' => 'ic_IC', 'name' => 'Iles Canaries',				'language' => 'Espagnol',				'nationality' => 'Canarienne'],
			['code' => 'in', 'locale' => 'in_IN', 'name' => 'Inde',							'language' => 'Hindi',					'nationality' => 'Indienne'],
			['code' => 'id', 'locale' => 'id_ID', 'name' => 'Indonésie',					'language' => 'Indonésien',				'nationality' => 'Indonésienne'],
			['code' => 'ww', 'locale' => 'fr_FR', 'name' => 'International',				'language' => 'NC.',					'nationality' => 'NC.'],
			['code' => 'iq', 'locale' => 'iq_IQ', 'name' => 'Irak',							'language' => 'Arabe',					'nationality' => 'Irakienne'],
			['code' => 'ir', 'locale' => 'ir_IR', 'name' => 'Iran',							'language' => 'Persan',					'nationality' => 'Iranienne'],
			['code' => 'ie', 'locale' => 'ie_IE', 'name' => 'Irlande',						'language' => 'Irlandais',				'nationality' => 'Irlandaise'],
			['code' => 'is', 'locale' => 'is_IS', 'name' => 'Islande',						'language' => 'Islandais',				'nationality' => 'Islandaise'],
			['code' => 'il', 'locale' => 'il_IL', 'name' => 'Israël',						'language' => 'Arabe',					'nationality' => 'Israelienne'],
			['code' => 'it', 'locale' => 'it_IT', 'name' => 'Italie',						'language' => 'Italien',				'nationality' => 'Italienne'],
			['code' => 'jm', 'locale' => 'jm_JM', 'name' => 'Jamaïque',						'language' => 'Anglais',				'nationality' => 'Jamaicaine'],
			['code' => 'jp', 'locale' => 'jp_JP', 'name' => 'Japon',						'language' => 'Japonais',				'nationality' => 'Japonaise'],
			['code' => 'je', 'locale' => 'je_JE', 'name' => 'Jersey',						'language' => 'Normand',				'nationality' => 'Jersiaise'],
			['code' => 'jo', 'locale' => 'jo_JO', 'name' => 'Jordanie',						'language' => 'Arabe',					'nationality' => 'Jordanienne'],
			['code' => 'kz', 'locale' => 'kz_KZ', 'name' => 'Kazakhstan',					'language' => 'Russe',					'nationality' => 'Kazakhstanaise'],
			['code' => 'ke', 'locale' => 'ke_KE', 'name' => 'Kenya',						'language' => 'Swahili',				'nationality' => 'Kenyane'],
			['code' => 'ki', 'locale' => 'ki_KI', 'name' => 'Kiribati',						'language' => 'Gilbertin',				'nationality' => 'Gilbertine'],
			['code' => 'kw', 'locale' => 'kw_KW', 'name' => 'Koweit',						'language' => 'Arabe',					'nationality' => 'Koweitienne'],
			['code' => 'kg', 'locale' => 'kg_KG', 'name' => 'Kyrgyzstan',					'language' => 'Kirghize',				'nationality' => 'Kirghize'],
			['code' => 'la', 'locale' => 'la_LA', 'name' => 'Laos',							'language' => 'Lao',					'nationality' => 'Laotienne'],
			['code' => 'lv', 'locale' => 'lv_LV', 'name' => 'Lettonie',						'language' => 'Letton',					'nationality' => 'Lettone'],
			['code' => 'le', 'locale' => 'le_LE', 'name' => 'Liban',						'language' => 'Arabe',					'nationality' => 'Libanaise'],
			['code' => 'lr', 'locale' => 'lr_LR', 'name' => 'Liberia',						'language' => 'Anglais',				'nationality' => 'Libérienne'],
			['code' => 'li', 'locale' => 'li_LI', 'name' => 'Liechtenstein',				'language' => 'Allemand',				'nationality' => 'Liechtenstein'],
			['code' => 'lt', 'locale' => 'lt_LT', 'name' => 'Lituanie',						'language' => 'Lituanien',				'nationality' => 'Lituanienne'],
			['code' => 'lu', 'locale' => 'lu_LU', 'name' => 'Luxembourg',					'language' => 'Luxembourgeois',			'nationality' => 'Luxembourgeoise'],
			['code' => 'ly', 'locale' => 'ly_LY', 'name' => 'Lybie',						'language' => 'Arabe',					'nationality' => 'Libyenne'],
			['code' => 'mo', 'locale' => 'mo_MO', 'name' => 'Macao',						'language' => 'Cantonais',				'nationality' => 'Macanaise'],
			['code' => 'mk', 'locale' => 'mk_MK', 'name' => 'Macedoine',					'language' => 'Macédonien',				'nationality' => 'Macédonienne'],
			['code' => 'mg', 'locale' => 'mg_MG', 'name' => 'Madagascar',					'language' => 'Malgache',				'nationality' => 'Malgache'],
			['code' => 'mw', 'locale' => 'mw_MW', 'name' => 'Malawi',						'language' => 'Chichewa',				'nationality' => 'Malawite'],
			['code' => 'my', 'locale' => 'my_MY', 'name' => 'Malaisie',						'language' => 'Malais',					'nationality' => 'Malaisienne'],
			['code' => 'mv', 'locale' => 'mv_MV', 'name' => 'Maldives',						'language' => 'Maldivien',				'nationality' => 'Maldivienne'],
			['code' => 'ml', 'locale' => 'ml_ML', 'name' => 'Mali',							'language' => 'Français',				'nationality' => 'Malienne'],
			['code' => 'mt', 'locale' => 'mt_MT', 'name' => 'Malte',						'language' => 'Maltais',				'nationality' => 'Maltaise'],
			['code' => 'ma', 'locale' => 'ma_MA', 'name' => 'Maroc',						'language' => 'Arabe',					'nationality' => 'Marocaine'],
			['code' => 'mr', 'locale' => 'mr_MR', 'name' => 'Mauritanie',					'language' => 'Arabe',					'nationality' => 'Mauritanienne'],
			['code' => 'mx', 'locale' => 'mx_MX', 'name' => 'Mexique',						'language' => 'Espagnol',				'nationality' => 'Mexicaine'],
			['code' => 'md', 'locale' => 'md_MD', 'name' => 'Moldavie',						'language' => 'Roumain',				'nationality' => 'Moldave'],
			['code' => 'mn', 'locale' => 'mn_MN', 'name' => 'Mongolie',						'language' => 'Mongol',					'nationality' => 'Mongolienne'],
			['code' => 'me', 'locale' => 'me_ME', 'name' => 'Montenegro',					'language' => 'Monténégrin',			'nationality' => 'Monténégrine'],
			['code' => 'mz', 'locale' => 'mz_MZ', 'name' => 'Mozambique',					'language' => 'Portugais',				'nationality' => 'Mozambicaine'],
			['code' => 'na', 'locale' => 'na_NA', 'name' => 'Namibie',						'language' => 'Anglais',				'nationality' => 'Namibienne'],
			['code' => 'np', 'locale' => 'np_NP', 'name' => 'Népal',						'language' => 'Népalais',				'nationality' => 'Népalaise'],
			['code' => 'ni', 'locale' => 'ni_NI', 'name' => 'Nicaragua',					'language' => 'Espagnol',				'nationality' => 'Nicaraguayenne'],
			['code' => 'ne', 'locale' => 'ne_NE', 'name' => 'Niger',						'language' => 'Français',				'nationality' => 'Nigérienne'],
			['code' => 'ng', 'locale' => 'ng_NG', 'name' => 'Nigéria',						'language' => 'Anglais',				'nationality' => 'Nigériane'],
			['code' => 'no', 'locale' => 'no_NO', 'name' => 'Norvège',						'language' => 'Norvégien',				'nationality' => 'Norvégienne'],
			['code' => 'nz', 'locale' => 'nz_NZ', 'name' => 'Nouvelle-Zélande',				'language' => 'Anglais',				'nationality' => 'Néozélandaise'],
			['code' => 'om', 'locale' => 'om_OM', 'name' => 'Oman',							'language' => 'Arabe',					'nationality' => 'Omanaise'],
			['code' => 'ug', 'locale' => 'ug_UG', 'name' => 'Ouganda',						'language' => 'Anglais',				'nationality' => 'Ougandaise'],
			['code' => 'uz', 'locale' => 'uz_UZ', 'name' => 'Ouzbekistan',					'language' => 'Ouzbek',					'nationality' => 'Ouzbèke'],
			['code' => 'pk', 'locale' => 'pk_PK', 'name' => 'Pakistan',						'language' => 'Ourdou',					'nationality' => 'Pakistanaise'],
			['code' => 'pa', 'locale' => 'pa_PA', 'name' => 'Panama',						'language' => 'Espagnol',				'nationality' => 'Panaméenne'],
			['code' => 'py', 'locale' => 'py_PY', 'name' => 'Paraguay',						'language' => 'Guarani',				'nationality' => 'Paraguayenne'],
			['code' => 'nl', 'locale' => 'nl_NL', 'name' => 'Pays-Bas',						'language' => 'Néerlandais',			'nationality' => 'Néerlandaise'],
			['code' => 'pe', 'locale' => 'pe_PE', 'name' => 'Pérou',						'language' => 'Espagnol',				'nationality' => 'Péruvienne'],
			['code' => 'ph', 'locale' => 'ph_PH', 'name' => 'Philippines',					'language' => 'Filipino',				'nationality' => 'Philippine'],
			['code' => 'pl', 'locale' => 'pl_PL', 'name' => 'Pologne',						'language' => 'Polonais',				'nationality' => 'Polonaise'],
			['code' => 'pt', 'locale' => 'pt_PT', 'name' => 'Portugal',						'language' => 'Portugais',				'nationality' => 'Portugaise'],
			['code' => 'pr', 'locale' => 'pr_PR', 'name' => 'Puerto Rico',					'language' => 'Espagnol',				'nationality' => 'Portoricaine'],
			['code' => 'qa', 'locale' => 'qa_QA', 'name' => 'Qatar',						'language' => 'Arabe',					'nationality' => 'Qatarienne'],
			['code' => 'cf', 'locale' => 'cf_CF', 'name' => 'République Centrafricaine',	'language' => 'Français',				'nationality' => 'Centrafricaine'],
			['code' => 'ro', 'locale' => 'ro_RO', 'name' => 'Roumanie',						'language' => 'Roumain',				'nationality' => 'Roumaine'],
			['code' => 'ru', 'locale' => 'ru_RU', 'name' => 'Russie',						'language' => 'Russe',					'nationality' => 'Russe'],
			['code' => 'rw', 'locale' => 'rw_RW', 'name' => 'Rwanda',						'language' => 'Kinyarwanda',			'nationality' => 'Rwandaise'],
			['code' => 'ws', 'locale' => 'ws_WS', 'name' => 'Samoa',						'language' => 'Samoan',					'nationality' => 'Samoane'],
			['code' => 'sm', 'locale' => 'sm_SM', 'name' => 'San Marin',					'language' => 'Italien',				'nationality' => 'Saint Marinaise'],
			['code' => 'sn', 'locale' => 'sn_SN', 'name' => 'Sénégal',						'language' => 'Français',				'nationality' => 'Sénégalaise'],
			['code' => 'rs', 'locale' => 'rs_RS', 'name' => 'Serbie',						'language' => 'Serbe',					'nationality' => 'Serbe'],
			['code' => 'sc', 'locale' => 'sc_SC', 'name' => 'Seychelles',					'language' => 'Créole Seychellois',		'nationality' => 'Seychelloise'],
			['code' => 'sl', 'locale' => 'sl_SL', 'name' => 'Sierra Leone',					'language' => 'Anglais',				'nationality' => 'Sierra-Léonaise'],
			['code' => 'sg', 'locale' => 'sg_SG', 'name' => 'Singapour',					'language' => 'Mandarin',				'nationality' => 'Singapourienne'],
			['code' => 'sk', 'locale' => 'sk_SK', 'name' => 'Slovaquie',					'language' => 'Slovaque',				'nationality' => 'Slovaque'],
			['code' => 'si', 'locale' => 'si_SI', 'name' => 'Slovénie',						'language' => 'Slovène',				'nationality' => 'Slovène'],
			['code' => 'so', 'locale' => 'so_SO', 'name' => 'Somalie',						'language' => 'Somali',					'nationality' => 'Somalienne'],
			['code' => 'sd', 'locale' => 'sd_SD', 'name' => 'Soudan',						'language' => 'Arabe',					'nationality' => 'Soudanaise'],
			['code' => 'lk', 'locale' => 'lk_LK', 'name' => 'Sri Lanka',					'language' => 'Cingalais',				'nationality' => 'Sri-Lankaise'],
			['code' => 'se', 'locale' => 'se_SE', 'name' => 'Suède',						'language' => 'Suédois',				'nationality' => 'Suédoise'],
			['code' => 'ch', 'locale' => 'ch_CH', 'name' => 'Suisse',						'language' => 'Français',				'nationality' => 'Suisse'],
			['code' => 'sr', 'locale' => 'sr_SR', 'name' => 'Suriname',						'language' => 'Néerlandais',			'nationality' => 'Surinamaise'],
			['code' => 'sz', 'locale' => 'sz_SZ', 'name' => 'Swaziland',					'language' => 'Swati',					'nationality' => 'Swazie'],
			['code' => 'sy', 'locale' => 'sy_SY', 'name' => 'Syrie',						'language' => 'Arabe',					'nationality' => 'Syrienne'],
			['code' => 'tw', 'locale' => 'tw_TW', 'name' => 'Taiwan',						'language' => 'Mandarin',				'nationality' => 'Taïwanaise'],
			['code' => 'tj', 'locale' => 'tj_TJ', 'name' => 'Tadjikistan',					'language' => 'Tadjik',					'nationality' => 'Tadjik'],
			['code' => 'tz', 'locale' => 'tz_TZ', 'name' => 'Tanzanie',						'language' => 'Swahili',				'nationality' => 'Tanzanienne'],
			['code' => 'td', 'locale' => 'td_TD', 'name' => 'Tchad',						'language' => 'Français',				'nationality' => 'Tchadienne'],
			['code' => 'cz', 'locale' => 'cz_CZ', 'name' => 'Tchécoslovaquie',				'language' => 'Tchèque',				'nationality' => 'Tchèque'],
			['code' => 'th', 'locale' => 'th_TH', 'name' => 'Thaïlande',					'language' => 'Thaï',					'nationality' => 'Thaïlandaise'],
			['code' => 'tl', 'locale' => 'tl_TL', 'name' => 'Timor Oriental',				'language' => 'Tétoum',					'nationality' => 'Timoraise'],
			['code' => 'tg', 'locale' => 'tg_TG', 'name' => 'Togo',							'language' => 'Français',				'nationality' => 'Togolaise'],
			['code' => 'to', 'locale' => 'to_TO', 'name' => 'Tonga',						'language' => 'Tongien',				'nationality' => 'Tongienne'],
			['code' => 'tt', 'locale' => 'tt_TT', 'name' => 'Trinité et Tobago',			'language' => 'Anglais',				'nationality' => 'Trinidadienne'],
			['code' => 'tn', 'locale' => 'tn_TN', 'name' => 'Tunisie',						'language' => 'Arabe',					'nationality' => 'Tunisienne'],
			['code' => 'tm', 'locale' => 'tm_TM', 'name' => 'Turkmenistan',					'language' => 'Turkmène',				'nationality' => 'Turkmène'],
			['code' => 'tr', 'locale' => 'tr_TR', 'name' => 'Turquie',						'language' => 'Turc',					'nationality' => 'Turque'],
			['code' => 'tv', 'locale' => 'tv_TV', 'name' => 'Tuvalu',						'language' => 'Tuvaluan',				'nationality' => 'Tuvaluane'],
			['code' => 'ua', 'locale' => 'ua_UA', 'name' => 'Ukraine',						'language' => 'Ukrainien',				'nationality' => 'Ukrainienne'],
			['code' => 'uy', 'locale' => 'uy_UY', 'name' => 'Uruguay',						'language' => 'Espagnol',				'nationality' => 'Uruguayenne'],
			['code' => 'us', 'locale' => 'us_US', 'name' => 'USA',							'language' => 'Anglais',				'nationality' => 'Américaine'],
			['code' => 'vu', 'locale' => 'vu_VU', 'name' => 'Vanuatu',						'language' => 'Bichelamar',				'nationality' => 'Vanuataise'],
			['code' => 've', 'locale' => 've_VE', 'name' => 'Venezuela',					'language' => 'Espagnol',				'nationality' => 'Venezuelienne'],
			['code' => 'vn', 'locale' => 'vn_VN', 'name' => 'Vietnam',						'language' => 'Vietnamien',				'nationality' => 'Vietnamienne'],
			['code' => 'ye', 'locale' => 'ye_YE', 'name' => 'Yemen',						'language' => 'Arabe',					'nationality' => 'Yéménite'],
			['code' => 'zm', 'locale' => 'zm_ZM', 'name' => 'Zambie',						'language' => 'Anglais',				'nationality' => 'Zambienne'],
			['code' => 'zw', 'locale' => 'zw_ZW', 'name' => 'Zimbabwe',						'language' => 'Anglais',				'nationality' => 'Zimbabwéenne']
		];
	}

	public function all(){
		return $this->data;
	}

	public function getByID($id){
		$data = array_filter($this->data, function($e) use ($id){
			return $id == $e['id'];
		});

		if(empty($data)) return false;

		$data = array_values($data);
		return $data[0];
	}

}