<?php

namespace YoVideo;

class Edition{

	private $data = [];

	public function __construct(){
		$this->setData();
	}

	public function setData(){
		$this->data = [
			['id' => 0,      'name' => 'Inconnu'],
			['id' => 27,     'name' => 'Blu-Ray'],
			['id' => 57,     'name' => 'Blu-Ray - 3D'],
			['id' => 131,    'name' => 'Blu-Ray - 3D - Edition Anniversaire'],
			['id' => 65,     'name' => 'Blu-Ray - 3D - Edition Collector'],
			['id' => 32,     'name' => 'Blu-Ray - 3D - Edition Limitée'],
			['id' => 100,    'name' => 'Blu-Ray - 3D - Edition Locative'],
			['id' => 113,    'name' => 'Blu-Ray - 3D - Edition Spéciale'],
			['id' => 172,    'name' => 'Blu-Ray - 3D - Edition SteelBook'],
			['id' => 63,     'name' => 'Blu-Ray - 3D - Ultimate Edition'],
			['id' => 33,     'name' => 'Blu-Ray - Coffret'],
			['id' => 52,     'name' => 'Blu-Ray - Director\'s Cut'],
			['id' => 140,    'name' => 'Blu-Ray - Edition 4K'],
			['id' => 50,     'name' => 'Blu-Ray - Edition Anniversaire'],
			['id' => 43,     'name' => 'Blu-Ray - Edition Collector'],
			['id' => 170,    'name' => 'Blu-Ray - Edition Collector Limitée'],
			['id' => 77,     'name' => 'Blu-Ray - Édition Commemorative'],
			['id' => 110,    'name' => 'Blu-Ray - Edition Définitive'],
			['id' => 48,     'name' => 'Blu-Ray - Edition Deluxe'],
			['id' => 117,    'name' => 'Blu-Ray - Edition Digibook'],
			['id' => 101,    'name' => 'Blu-Ray - Edition Double'],
			['id' => 190,    'name' => 'Blu-Ray - Edition Exclusive'],
			['id' => 184,    'name' => 'Blu-Ray - Edition Extrême'],
			['id' => 151,    'name' => 'Blu-Ray - Edition Gold'],
			['id' => 39,     'name' => 'Blu-Ray - Edition Limitée'],
			['id' => 30,     'name' => 'Blu-Ray - Edition Locative'],
			['id' => 98,     'name' => 'Blu-Ray - Edition Premium'],
			['id' => 54,     'name' => 'Blu-Ray - Edition Prestige'],
			['id' => 56,     'name' => 'Blu-Ray - Edition Remasterisée'],
			['id' => 61,     'name' => 'Blu-Ray - Edition Restaurée'],
			['id' => 125,    'name' => 'Blu-Ray - Edition Saphir'],
			['id' => 153,    'name' => 'Blu-Ray - Edition Simple'],
			['id' => 159,    'name' => 'Blu-Ray - Edition Single'],
			['id' => 53,     'name' => 'Blu-Ray - Edition Spéciale'],
			['id' => 168,    'name' => 'Blu-Ray - Edition Spéciale AMAZON'],
			['id' => 167,    'name' => 'Blu-Ray - Edition Spéciale FNAC'],
			['id' => 74,     'name' => 'Blu-Ray - Edition Standard'],
			['id' => 122,    'name' => 'Blu-Ray - Edition Steelbook'],
			['id' => 51,     'name' => 'Blu-Ray - Pack Spécial'],
			['id' => 42,     'name' => 'Blu-Ray - Ultimate Edition'],
			['id' => 58,     'name' => 'Blu-Ray - Version intégrale'],
			['id' => 59,     'name' => 'Blu-Ray - Version longue'],
			['id' => 72,     'name' => 'Blu-Ray + Copie Digitale'],
			['id' => 175,    'name' => 'Blu-Ray + Copie Digitale - Edition SteelBook'],
			['id' => 183,    'name' => 'Blu-Ray + Copie Digitale - Ultraviolet'],
			['id' => 192,    'name' => 'Blu-Ray + Copie Digitale - Version Longue'],
			['id' => 439,    'name' => 'Blu-Ray - Edition Finale'],
			['id' => 440,    'name' => 'Blu-Ray - Edition Numérotée'],

			['id' => 78,     'name' => 'CD Audio'],
			['id' => 55,     'name' => 'CD-Rom'],

			['id' => 35,     'name' => 'Combo - Blu-Ray + DVD'],
			['id' => 70,     'name' => 'Combo - Blu-Ray + DVD - Director\'s cut'],
			['id' => 186,    'name' => 'Combo - Blu-Ray + DVD - Edition Anniversaire'],
			['id' => 68,     'name' => 'Combo - Blu-Ray + DVD - Edition Collector'],
			['id' => 176,    'name' => 'Combo - Blu-Ray + DVD - Edition Collector Limitée'],
			['id' => 150,    'name' => 'Combo - Blu-Ray + DVD - Edition Comic Book'],
			['id' => 111,    'name' => 'Combo - Blu-Ray + DVD - Edition Deluxe'],
			['id' => 181,    'name' => 'Combo - Blu-Ray + DVD - Edition Digibook'],
			['id' => 69,     'name' => 'Combo - Blu-Ray + DVD - Edition Limitée'],
			['id' => 80,     'name' => 'Combo - Blu-Ray + DVD - Edition Locative'],
			['id' => 67,     'name' => 'Combo - Blu-Ray + DVD - Edition Prestige'],
			['id' => 155,    'name' => 'Combo - Blu-Ray + DVD - Edition Simple'],
			['id' => 97,     'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale'],
			['id' => 166,    'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale AMAZON'],
			['id' => 169,    'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale FNAC'],
			['id' => 118,    'name' => 'Combo - Blu-Ray + DVD - Edition SteelBook'],
			['id' => 79,     'name' => 'Combo - Blu-Ray + DVD - Ultimate Edition'],
			['id' => 139,    'name' => 'Combo - Blu-Ray + DVD - Version longue'],
			['id' => 173,    'name' => 'Combo - Blu-Ray + DVD + CD Audio'],
			['id' => 83,     'name' => 'Combo - Blu-Ray + DVD + Copie Digitale'],
			['id' => 75,     'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Director\'s Cut'],
			['id' => 137,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Collector'],
			['id' => 121,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Digibook'],
			['id' => 112,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Limitée'],
			['id' => 142,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Prestige'],
			['id' => 114,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Spéciale'],
			['id' => 180,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 119,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Steelbook'],
			['id' => 99,     'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Ultimate Edition'],
			['id' => 134,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Version Longue'],
			['id' => 174,    'name' => 'Combo - Blu-ray + DVD + Copie Digitale + CD - Edition Steelbook'],
			['id' => 200,    'name' => 'Combo - Blu-Ray + DVD - Edition Commémorative'],
			['id' => 201,    'name' => 'Combo - Blu-Ray + DVD - Edition Exclusive'],
			['id' => 202,    'name' => 'Combo - Blu-Ray + DVD - Edition Finale'],
			['id' => 203,    'name' => 'Combo - Blu-Ray + DVD - Edition Numérotée'],
			['id' => 204,    'name' => 'Combo - Blu-Ray + DVD - Edition Remasterisée'],
			['id' => 205,    'name' => 'Combo - Blu-Ray + DVD - Edition Restaurée'],
			['id' => 206,    'name' => 'Combo - Blu-Ray + DVD - Edition Single'],
			['id' => 207,    'name' => 'Combo - Blu-Ray + DVD - Edition Standard'],
			['id' => 208,    'name' => 'Combo - Blu-Ray + DVD - Pack Spécial'],
			['id' => 209,    'name' => 'Combo - Blu-Ray + DVD - Version Intégrale'],
			['id' => 210,    'name' => 'Combo - Blu-Ray + DVD + Livre'],
			['id' => 211,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Anniversaire'],
			['id' => 212,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Collector Limitée'],
			['id' => 213,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Commémorative'],
			['id' => 214,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Deluxe'],
			['id' => 215,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Exclusive'],
			['id' => 216,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Finale'],
			['id' => 217,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Numérotée'],
			['id' => 218,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Remasterisée'],
			['id' => 219,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Restaurée'],
			['id' => 220,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Simple'],
			['id' => 221,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Single'],
			['id' => 222,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 223,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Standard'],
			['id' => 224,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Pack Spécial'],
			['id' => 225,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Version Intégrale'],
			['id' => 226,    'name' => 'Combo - Blu-Ray + DVD + Copie Digitale + Livre'],
			['id' => 227,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Collector Limitée'],
			['id' => 228,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Commémorative'],
			['id' => 229,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Deluxe'],
			['id' => 230,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Digibook'],
			['id' => 231,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Exclusive'],
			['id' => 232,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Finale'],
			['id' => 233,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Limitée'],
			['id' => 234,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Numérotée'],
			['id' => 235,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Prestige'],
			['id' => 236,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Remasterisée'],
			['id' => 237,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Restaurée'],
			['id' => 238,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Simple'],
			['id' => 239,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Single'],
			['id' => 240,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Spéciale AMAZON'],
			['id' => 241,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Standard'],
			['id' => 242,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Pack Spécial'],
			['id' => 243,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Ultimate Edition'],
			['id' => 244,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Version Intégrale'],
			['id' => 245,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Version Longue'],
			['id' => 246,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Livre'],
			['id' => 247,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Director\'s Cut'],
			['id' => 248,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Anniversaire'],
			['id' => 249,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Collector'],
			['id' => 250,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Collector Limitée'],
			['id' => 251,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Commémorative'],
			['id' => 252,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Deluxe'],
			['id' => 253,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Digibook'],
			['id' => 254,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Exclusive'],
			['id' => 255,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Finale'],
			['id' => 256,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Limitée'],
			['id' => 257,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Numérotée'],
			['id' => 258,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Prestige'],
			['id' => 259,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Remasterisée'],
			['id' => 260,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Restaurée'],
			['id' => 261,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Simple'],
			['id' => 262,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Single'],
			['id' => 263,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Spéciale'],
			['id' => 264,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 265,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 266,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Edition Standard'],
			['id' => 267,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Pack Spécial'],
			['id' => 268,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Ultimate Edition'],
			['id' => 269,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Version Intégrale'],
			['id' => 270,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale - Version Longue'],
			['id' => 271,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale + Livre'],
			['id' => 272,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Director\'s Cut'],
			['id' => 273,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Anniversaire'],
			['id' => 274,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Collector Limitée'],
			['id' => 275,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Commémorative'],
			['id' => 276,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Deluxe'],
			['id' => 277,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Digibook'],
			['id' => 278,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Exclusive'],
			['id' => 279,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Finale'],
			['id' => 280,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Numérotée'],
			['id' => 281,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Prestige'],
			['id' => 282,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Remasterisée'],
			['id' => 283,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Restaurée'],
			['id' => 284,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Simple'],
			['id' => 285,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Single'],
			['id' => 286,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Spéciale FNAC'],
			['id' => 287,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Spéciale AMAZON'],
			['id' => 288,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Standard'],
			['id' => 289,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Pack Spécial'],
			['id' => 290,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Version Intégrale'],
			['id' => 291,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Livre'],
			['id' => 292,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Director\'s Cut'],
			['id' => 293,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Anniversaire'],
			['id' => 294,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Collector'],
			['id' => 295,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Collector Limitée'],
			['id' => 296,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Commémorative'],
			['id' => 297,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Deluxe'],
			['id' => 298,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Digibook'],
			['id' => 299,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Exclusive'],
			['id' => 300,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Finale'],
			['id' => 301,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Numérotée'],
			['id' => 302,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Prestige'],
			['id' => 303,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Remasterisée'],
			['id' => 304,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Restaurée'],
			['id' => 305,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Simple'],
			['id' => 306,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Single'],
			['id' => 307,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 308,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 309,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Standard'],
			['id' => 310,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Pack Spécial'],
			['id' => 311,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Version Intégrale'],
			['id' => 312,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale + Livre'],
			['id' => 313,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Director\'s Cut'],
			['id' => 314,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Anniversaire'],
			['id' => 315,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Collector'],
			['id' => 316,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Collector Limitée'],
			['id' => 317,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Commémorative'],
			['id' => 318,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Deluxe'],
			['id' => 319,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Digibook'],
			['id' => 320,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Exclusive'],
			['id' => 321,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Finale'],
			['id' => 322,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Limitée'],
			['id' => 323,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Numérotée'],
			['id' => 324,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Prestige'],
			['id' => 325,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Remasterisée'],
			['id' => 326,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Restaurée'],
			['id' => 327,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Simple'],
			['id' => 328,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Single'],
			['id' => 329,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Spéciale'],
			['id' => 330,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 331,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 332,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Standard'],
			['id' => 333,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Pack Spécial'],
			['id' => 334,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Ultimate Edition'],
			['id' => 335,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Version Intégrale'],
			['id' => 336,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Version Longue'],
			['id' => 337,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale + Livre'],
			['id' => 338,    'name' => 'Combo - Blu-Ray 3D + DVD - Director\'s Cut'],
			['id' => 339,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Anniversaire'],
			['id' => 340,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Collector Limitée'],
			['id' => 341,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Commémorative'],
			['id' => 342,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Deluxe'],
			['id' => 343,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Digibook'],
			['id' => 344,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Exclusive'],
			['id' => 345,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Finale'],
			['id' => 346,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Numérotée'],
			['id' => 347,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Prestige'],
			['id' => 348,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Remasterisée'],
			['id' => 349,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Restaurée'],
			['id' => 350,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Simple'],
			['id' => 351,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Single'],
			['id' => 352,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Spéciale'],
			['id' => 353,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Spéciale FNAC'],
			['id' => 354,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Spéciale AMAZON'],
			['id' => 355,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Standard'],
			['id' => 356,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Steelbook'],
			['id' => 357,    'name' => 'Combo - Blu-Ray 3D + DVD - Pack Spécial'],
			['id' => 358,    'name' => 'Combo - Blu-Ray 3D + DVD - Ultimate Edition'],
			['id' => 359,    'name' => 'Combo - Blu-Ray 3D + DVD - Version Intégrale'],
			['id' => 360,    'name' => 'Combo - Blu-Ray 3D + DVD - Version Longue'],
			['id' => 361,    'name' => 'Combo - Blu-Ray 3D + DVD + Livre'],
			['id' => 362,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Director\'s Cut'],
			['id' => 363,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Anniversaire'],
			['id' => 364,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Collector'],
			['id' => 365,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Collector Limitée'],
			['id' => 366,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Commémorative'],
			['id' => 367,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Deluxe'],
			['id' => 368,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Digibook'],
			['id' => 369,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Exclusive'],
			['id' => 370,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Finale'],
			['id' => 371,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Limitée'],
			['id' => 372,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Numérotée'],
			['id' => 373,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Prestige'],
			['id' => 374,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Remasterisée'],
			['id' => 375,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Restaurée'],
			['id' => 376,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Simple'],
			['id' => 377,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Single'],
			['id' => 378,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Spéciale'],
			['id' => 379,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 380,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 381,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Standard'],
			['id' => 382,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Edition Steelbook'],
			['id' => 383,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Pack Spécial'],
			['id' => 384,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Ultimate Edition'],
			['id' => 385,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Version Intégrale'],
			['id' => 386,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale - Version Longue'],
			['id' => 387,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale + Livre'],
			['id' => 81,     'name' => 'Combo - Blu-Ray 3D + Blu-Ray'],
			['id' => 189,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Director\'s Cut'],
			['id' => 129,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Anniversaire'],
			['id' => 143,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Collector'],
			['id' => 135,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Spéciale'],
			['id' => 171,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Spéciale FNAC'],
			['id' => 179,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Steelbook'],
			['id' => 82,     'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale'],
			['id' => 188,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie digitale - Édition SteelBook'],
			['id' => 62,     'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD'],
			['id' => 157,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Collector'],
			['id' => 136,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Limitée'],
			['id' => 66,     'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Spéciale'],
			['id' => 126,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Steelbook'],
			['id' => 120,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Ultimate edition'],
			['id' => 138,    'name' => 'Combo - Blu-Ray 3D + Blu-ray + DVD - Version longue'],
			['id' => 102,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale'],
			['id' => 196,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Limitée'],
			['id' => 132,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Spéciale'],
			['id' => 128,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Steelbook'],
			['id' => 109,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Ultimate Edition'],
			['id' => 133,    'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Version Longue'],
			['id' => 127,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale'],
			['id' => 187,    'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Steelbook'],
			['id' => 64,     'name' => 'Combo - Blu-Ray 3D + DVD'],
			['id' => 178,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Collector'],
			['id' => 195,    'name' => 'Combo - Blu-Ray 3D + DVD - Edition Limitée'],
			['id' => 106,    'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale'],

			['id' => 46,     'name' => 'DivX - DVDrip'],
			['id' => 47,     'name' => 'DivX - RS'],

			['id' => 1,      'name' => 'DVD'],
			['id' => 177,    'name' => 'DVD - 3D'],
			['id' => 103,    'name' => 'DVD - 3D - Edition Collector'],
			['id' => 105,    'name' => 'DVD - 3D - Edition Collector Limitée'],
			['id' => 104,    'name' => 'DVD - 3D - Edition Limitée'],
			['id' => 73,     'name' => 'DVD - 3D - Edition Simple'],
			['id' => 147,    'name' => 'DVD - 3D - Edition Spéciale'],
			['id' => 45,     'name' => 'DVD - Bonus'],
			['id' => 20,     'name' => 'DVD - Coffret'],
			['id' => 182,    'name' => 'DVD - Coffret Spindle'],
			['id' => 148,    'name' => 'DVD - Combo Programme'],
			['id' => 2,      'name' => 'DVD - Director\'s Cut'],
			['id' => 21,     'name' => 'DVD - Edition 2 DVD'],
			['id' => 197,    'name' => 'DVD - Edition 4K'],
			['id' => 24,     'name' => 'DVD - Edition Anniversaire'],
			['id' => 115,    'name' => 'DVD - Edition Anthologie'],
			['id' => 8,      'name' => 'DVD - Edition Collector'],
			['id' => 163,    'name' => 'DVD - Edition Collector Limitée'],
			['id' => 76,     'name' => 'DVD - Édition Commemorative'],
			['id' => 5,      'name' => 'DVD - Edition De Luxe'],
			['id' => 107,    'name' => 'DVD - Edition Définitive'],
			['id' => 144,    'name' => 'DVD - Edition Digibook'],
			['id' => 44,     'name' => 'DVD - Edition Digipack'],
			['id' => 18,     'name' => 'DVD - Edition Double'],
			['id' => 108,    'name' => 'DVD - Edition Ephémère'],
			['id' => 25,     'name' => 'DVD - Edition Exclusive'],
			['id' => 17,     'name' => 'DVD - Edition Extrême'],
			['id' => 116,    'name' => 'DVD - Edition Finale'],
			['id' => 124,    'name' => 'DVD - Edition Gold'],
			['id' => 11,     'name' => 'DVD - Edition Limitée'],
			['id' => 10,     'name' => 'DVD - Edition Locative'],
			['id' => 16,     'name' => 'DVD - Edition Numérotée'],
			['id' => 29,     'name' => 'DVD - Edition Platinum'],
			['id' => 160,    'name' => 'DVD - Edition Premium'],
			['id' => 3,      'name' => 'DVD - Edition Prestige'],
			['id' => 31,     'name' => 'DVD - Edition Remasterisée'],
			['id' => 60,     'name' => 'DVD - Edition Restaurée'],
			['id' => 152,    'name' => 'DVD - Edition Simple'],
			['id' => 4,      'name' => 'DVD - Edition Single'],
			['id' => 15,     'name' => 'DVD - Edition Spéciale'],
			['id' => 165,    'name' => 'DVD - Edition Spéciale AMAZON'],
			['id' => 164,    'name' => 'DVD - Edition Spéciale FNAC'],
			['id' => 9,      'name' => 'DVD - Edition Standard'],
			['id' => 123,    'name' => 'DVD - Edition Steelbook'],
			['id' => 14,     'name' => 'DVD - Edition Triple'],
			['id' => 26,     'name' => 'DVD - Mid Price'],
			['id' => 156,    'name' => 'DVD - Mon petit cinéma'],
			['id' => 13,     'name' => 'DVD - Pack Spécial'],
			['id' => 19,     'name' => 'DVD - Ultimate Edition'],
			['id' => 23,     'name' => 'DVD - Version Intégrale'],
			['id' => 12,     'name' => 'DVD - Version Longue'],
			['id' => 141,    'name' => 'DVD - WB Environmental'],
			['id' => 161,    'name' => 'DVD + CD Audio'],
			['id' => 71,     'name' => 'DVD + Copie Digitale'],
			['id' => 162,    'name' => 'DVD + Etui baladeur MP3'],
			['id' => 193,    'name' => 'DVD + Goodies'],
			['id' => 194,    'name' => 'DVD + Livre'],
			['id' => 146,    'name' => 'DVD + UMD'],
			['id' => 388,    'name' => 'DVD + Copie Digitale - Director\'s Cut'],
			['id' => 389,    'name' => 'DVD + Copie Digitale - Edition Anniversaire'],
			['id' => 390,    'name' => 'DVD + Copie Digitale - Edition Collector'],
			['id' => 391,    'name' => 'DVD + Copie Digitale - Edition Collector Limitée'],
			['id' => 392,    'name' => 'DVD + Copie Digitale - Edition Commémorative'],
			['id' => 393,    'name' => 'DVD + Copie Digitale - Edition Deluxe'],
			['id' => 394,    'name' => 'DVD + Copie Digitale - Edition Digibook'],
			['id' => 395,    'name' => 'DVD + Copie Digitale - Edition Exclusive'],
			['id' => 396,    'name' => 'DVD + Copie Digitale - Edition Finale'],
			['id' => 397,    'name' => 'DVD + Copie Digitale - Edition Limitée'],
			['id' => 398,    'name' => 'DVD + Copie Digitale - Edition Numérotée'],
			['id' => 399,    'name' => 'DVD + Copie Digitale - Edition Prestige'],
			['id' => 400,    'name' => 'DVD + Copie Digitale - Edition Remasterisée'],
			['id' => 401,    'name' => 'DVD + Copie Digitale - Edition Restaurée'],
			['id' => 402,    'name' => 'DVD + Copie Digitale - Edition Simple'],
			['id' => 403,    'name' => 'DVD + Copie Digitale - Edition Single'],
			['id' => 404,    'name' => 'DVD + Copie Digitale - Edition Spéciale'],
			['id' => 405,    'name' => 'DVD + Copie Digitale - Edition Spéciale FNAC'],
			['id' => 406,    'name' => 'DVD + Copie Digitale - Edition Spéciale AMAZON'],
			['id' => 407,    'name' => 'DVD + Copie Digitale - Edition Standard'],
			['id' => 408,    'name' => 'DVD + Copie Digitale - Edition Steelbook'],
			['id' => 409,    'name' => 'DVD + Copie Digitale - Pack Spécial'],
			['id' => 410,    'name' => 'DVD + Copie Digitale - Ultimate Edition'],
			['id' => 411,    'name' => 'DVD + Copie Digitale - Version Intégrale'],
			['id' => 412,    'name' => 'DVD + Copie Digitale - Version Longue'],

			['id' => 185,    'name' => 'DVD-Rom'],
			['id' => 28,     'name' => 'HD-DVD'],
			['id' => 130,    'name' => 'HD-DVD - Edition Collector'],
			['id' => 154,    'name' => 'HD-DVD - Edition Simple'],
			['id' => 145,    'name' => 'HD-DVD - Edition Spéciale'],
			['id' => 158,    'name' => 'Pack Duo - Blu-Ray + DVD'],

			['id' => 95,     'name' => 'JEU - 3DS'],
			['id' => 94,     'name' => 'JEU - DS'],
			['id' => 93,     'name' => 'JEU - LCM'],
			['id' => 92,     'name' => 'JEU - PC'],
			['id' => 91,     'name' => 'JEU - PS2'],
			['id' => 88,     'name' => 'JEU - PS3'],
			['id' => 87,     'name' => 'JEU - PSP'],
			['id' => 86,     'name' => 'JEU - PSvita'],
			['id' => 85,     'name' => 'JEU - Wii'],
			['id' => 96,     'name' => 'JEU - Wii U'],
			['id' => 84,     'name' => 'JEU - Xbox 360'],

			['id' => 38,     'name' => 'PDR - Blu-Ray'],
			['id' => 37,     'name' => 'PDR - DVD'],
			['id' => 36,     'name' => 'PDR - VHS'],
			['id' => 49,     'name' => 'Superbit'],
			['id' => 7,      'name' => 'UMD'],
			['id' => 22,     'name' => 'VHS'],
			['id' => 191,    'name' => 'VHS - Edition Simple'],

			
			['id' => 413,    'name' => '4K'],
			['id' => 414,    'name' => '4K - Director\'s Cut'],
			['id' => 415,    'name' => '4K - Edition Anniversaire'],
			['id' => 416,    'name' => '4K - Edition Collector'],
			['id' => 417,    'name' => '4K - Edition Collector Limitée'],
			['id' => 418,    'name' => '4K - Edition Commémorative'],
			['id' => 419,    'name' => '4K - Edition Deluxe'],
			['id' => 420,    'name' => '4K - Edition Digibook'],
			['id' => 421,    'name' => '4K - Edition Exclusive'],
			['id' => 422,    'name' => '4K - Edition Finale'],
			['id' => 423,    'name' => '4K - Edition Limitée'],
			['id' => 424,    'name' => '4K - Edition Numérotée'],
			['id' => 425,    'name' => '4K - Edition Prestige'],
			['id' => 426,    'name' => '4K - Edition Remasterisée'],
			['id' => 427,    'name' => '4K - Edition Restaurée'],
			['id' => 428,    'name' => '4K - Edition Simple'],
			['id' => 429,    'name' => '4K - Edition Single'],
			['id' => 430,    'name' => '4K - Edition Spéciale'],
			['id' => 431,    'name' => '4K - Edition Spéciale FNAC'],
			['id' => 432,    'name' => '4K - Edition Spéciale AMAZON'],
			['id' => 433,    'name' => '4K - Edition Standard'],
			['id' => 434,    'name' => '4K - Edition Steelbook'],
			['id' => 435,    'name' => '4K - Pack Spécial'],
			['id' => 436,    'name' => '4K - Ultimate Edition'],
			['id' => 437,    'name' => '4K - Version Intégrale'],
			['id' => 438,    'name' => '4K - Version Longue']
		];
	}

	public function all(){

		$data = $this->data;

		usort($data, function($a, $b){
			if($a['name'] == $b['name']) return 0;
			return $a['name'] > $b['name'] ? 1 : -1;
		});

		return $data;
	}

	public function getByID($id){
		$data = array_filter($this->data, function($e) use ($id){
			return $id == $e['id'];
		});

		if(empty($data)) return false;

		$data = array_values($data);
		return $data[0];
	}

	static function title($support){
	#	pre($support['types'], $support['edition']);

		$types = implode(' + ', $support['types']);
		if(!empty($types)) $types .= ' ';

		return $types . $support['edition'];
	}
}