<?php

namespace YoVideo;

class Edition{

	private $data = [];

	public function __construct(){
		$this->setData();
	}

	public function setData(){
		$this->data = [
			['id' => 0, 'name' => 'Inconnu'], 
			['id' => 27, 'name' => 'Blu-Ray'], 
			['id' => 57, 'name' => 'Blu-Ray - 3D'], 
			['id' => 131, 'name' => 'Blu-Ray - 3D - Edition Anniversaire'], 
			['id' => 65, 'name' => 'Blu-Ray - 3D - Edition Collector'], 
			['id' => 32, 'name' => 'Blu-Ray - 3D - Edition Limitée'], 
			['id' => 100, 'name' => 'Blu-Ray - 3D - Edition Locative'], 
			['id' => 113, 'name' => 'Blu-Ray - 3D - Edition Spéciale'], 
			['id' => 172, 'name' => 'Blu-Ray - 3D - Edition SteelBook'], 
			['id' => 63, 'name' => 'Blu-Ray - 3D - Ultimate Edition'], 
			['id' => 33, 'name' => 'Blu-Ray - Coffret'], 
			['id' => 52, 'name' => 'Blu-Ray - Director\'s Cut'], 
			['id' => 140, 'name' => 'Blu-Ray - Edition 4K'], 
			['id' => 50, 'name' => 'Blu-Ray - Edition Anniversaire'], 
			['id' => 43, 'name' => 'Blu-Ray - Edition Collector'], 
			['id' => 170, 'name' => 'Blu-Ray - Edition Collector Limitée'], 
			['id' => 77, 'name' => 'Blu-Ray - Édition Commemorative'], 
			['id' => 110, 'name' => 'Blu-Ray - Edition Définitive'], 
			['id' => 48, 'name' => 'Blu-Ray - Edition Deluxe'], 
			['id' => 117, 'name' => 'Blu-Ray - Edition Digibook'], 
			['id' => 101, 'name' => 'Blu-Ray - Edition Double'], 
			['id' => 190, 'name' => 'Blu-Ray - Edition Exclusive'], 
			['id' => 184, 'name' => 'Blu-Ray - Edition Extrême'], 
			['id' => 151, 'name' => 'Blu-Ray - Edition Gold'], 
			['id' => 39, 'name' => 'Blu-Ray - Edition Limitée'], 
			['id' => 30, 'name' => 'Blu-Ray - Edition Locative'], 
			['id' => 98, 'name' => 'Blu-Ray - Edition Premium'], 
			['id' => 54, 'name' => 'Blu-Ray - Edition Prestige'], 
			['id' => 56, 'name' => 'Blu-Ray - Edition Remasterisée'], 
			['id' => 61, 'name' => 'Blu-Ray - Edition Restaurée'], 
			['id' => 125, 'name' => 'Blu-Ray - Edition Saphir'], 
			['id' => 153, 'name' => 'Blu-Ray - Edition Simple'], 
			['id' => 159, 'name' => 'Blu-Ray - Edition Single'], 
			['id' => 53, 'name' => 'Blu-Ray - Edition Spéciale'], 
			['id' => 168, 'name' => 'Blu-Ray - Edition Spéciale AMAZON'], 
			['id' => 167, 'name' => 'Blu-Ray - Edition Spéciale FNAC'], 
			['id' => 74, 'name' => 'Blu-Ray - Edition Standard'], 
			['id' => 122, 'name' => 'Blu-Ray - Edition Steelbook'], 
			['id' => 51, 'name' => 'Blu-Ray - Pack Spécial'], 
			['id' => 42, 'name' => 'Blu-Ray - Ultimate Edition'], 
			['id' => 58, 'name' => 'Blu-Ray - Version intégrale'], 
			['id' => 59, 'name' => 'Blu-Ray - Version longue'], 
			['id' => 72, 'name' => 'Blu-Ray + Copie Digitale'], 
			['id' => 175, 'name' => 'Blu-Ray + Copie Digitale - Edition SteelBook'], 
			['id' => 183, 'name' => 'Blu-Ray + Copie Digitale - Ultraviolet'], 
			['id' => 192, 'name' => 'Blu-Ray + Copie Digitale - Version Longue'], 

			['id' => 78, 'name' => 'CD Audio'],
			['id' => 55, 'name' => 'CD-Rom'], 

			['id' => 35, 'name' => 'Combo - Blu-Ray + DVD'],
			['id' => 70, 'name' => 'Combo - Blu-Ray + DVD - Director\'s cut'],
			['id' => 186, 'name' => 'Combo - Blu-Ray + DVD - Edition Anniversaire'], 
			['id' => 68, 'name' => 'Combo - Blu-Ray + DVD - Edition Collector'], 
			['id' => 176, 'name' => 'Combo - Blu-Ray + DVD - Edition Collector Limitée'], 
			['id' => 150, 'name' => 'Combo - Blu-Ray + DVD - Edition Comic Book'], 
			['id' => 111, 'name' => 'Combo - Blu-Ray + DVD - Edition Deluxe'], 
			['id' => 181, 'name' => 'Combo - Blu-Ray + DVD - Edition Digibook'], 
			['id' => 69, 'name' => 'Combo - Blu-Ray + DVD - Edition Limitée'], 
			['id' => 80, 'name' => 'Combo - Blu-Ray + DVD - Edition Locative'], 
			['id' => 67, 'name' => 'Combo - Blu-Ray + DVD - Edition Prestige'], 
			['id' => 155, 'name' => 'Combo - Blu-Ray + DVD - Edition Simple'], 
			['id' => 97, 'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale'], 
			['id' => 166, 'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale AMAZON'], 
			['id' => 169, 'name' => 'Combo - Blu-Ray + DVD - Edition Spéciale FNAC'], 
			['id' => 118, 'name' => 'Combo - Blu-Ray + DVD - Edition SteelBook'], 
			['id' => 79, 'name' => 'Combo - Blu-Ray + DVD - Ultimate Edition'], 
			['id' => 139, 'name' => 'Combo - Blu-Ray + DVD - Version longue'], 
			['id' => 173, 'name' => 'Combo - Blu-Ray + DVD + CD Audio'], 
			['id' => 83, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale'], 
			['id' => 75, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Director\'s Cut'],
			['id' => 137, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Collector'], 
			['id' => 121, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Digibook'], 
			['id' => 112, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Limitée'], 
			['id' => 142, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Prestige'], 
			['id' => 114, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Spéciale'], 
			['id' => 180, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Spéciale FNAC'], 
			['id' => 119, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Edition Steelbook'], 
			['id' => 99, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Ultimate Edition'], 
			['id' => 134, 'name' => 'Combo - Blu-Ray + DVD + Copie Digitale - Version Longue'], 
			['id' => 174, 'name' => 'Combo - Blu-ray + DVD + Copie Digitale + CD - Edition Steelbook'], 
			['id' => 81, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray'], 
			['id' => 189, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Director\'s Cut'],
			['id' => 129, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Anniversaire'], 
			['id' => 143, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Collector'], 
			['id' => 135, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Spéciale'], 
			['id' => 171, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Spéciale FNAC'], 
			['id' => 179, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray - Edition Steelbook'], 
			['id' => 82, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie Digitale'], 
			['id' => 188, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + Copie digitale - Édition SteelBook'], 
			['id' => 62, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD'], 
			['id' => 157, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Collector'], 
			['id' => 136, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Limitée'], 
			['id' => 66, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Spéciale'], 
			['id' => 126, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Edition Steelbook'], 
			['id' => 120, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD - Ultimate edition'], 
			['id' => 138, 'name' => 'Combo - Blu-Ray 3D + Blu-ray + DVD - Version longue'], 
			['id' => 102, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale'], 
			['id' => 196, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Limitée'], 
			['id' => 132, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Spéciale'], 
			['id' => 128, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Edition Steelbook'], 
			['id' => 109, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Ultimate Edition'], 
			['id' => 133, 'name' => 'Combo - Blu-Ray 3D + Blu-Ray + DVD + Copie Digitale - Version Longue'], 
			['id' => 127, 'name' => 'Combo - Blu-Ray 3D + Copie Digitale'], 
			['id' => 187, 'name' => 'Combo - Blu-Ray 3D + Copie Digitale - Edition Steelbook'], 
			['id' => 64, 'name' => 'Combo - Blu-Ray 3D + DVD'], 
			['id' => 178, 'name' => 'Combo - Blu-Ray 3D + DVD - Edition Collector'], 
			['id' => 195, 'name' => 'Combo - Blu-Ray 3D + DVD - Edition Limitée'], 
			['id' => 106, 'name' => 'Combo - Blu-Ray 3D + DVD + Copie Digitale'], 
			['id' => 46, 'name' => 'DivX - DVDrip'], 
			['id' => 47, 'name' => 'DivX - RS'], 
			['id' => 1, 'name' => 'DVD'],
			['id' => 177, 'name' => 'DVD - 3D'], 
			['id' => 103, 'name' => 'DVD - 3D - Edition Collector'], 
			['id' => 105, 'name' => 'DVD - 3D - Edition Collector Limitée'], 
			['id' => 104, 'name' => 'DVD - 3D - Edition Limitée'], 
			['id' => 73, 'name' => 'DVD - 3D - Edition Simple'], 
			['id' => 147, 'name' => 'DVD - 3D - Edition Spéciale'], 
			['id' => 45, 'name' => 'DVD - Bonus'], 
			['id' => 20, 'name' => 'DVD - Coffret'], 
			['id' => 182, 'name' => 'DVD - Coffret Spindle'], 
			['id' => 148, 'name' => 'DVD - Combo Programme'], 
			['id' => 2, 'name' => 'DVD - Director\'s Cut'],
			['id' => 21, 'name' => 'DVD - Edition 2 DVD'], 
			['id' => 197, 'name' => 'DVD - Edition 4K'], 
			['id' => 24, 'name' => 'DVD - Edition Anniversaire'], 
			['id' => 115, 'name' => 'DVD - Edition Anthologie'], 
			['id' => 8, 'name' => 'DVD - Edition Collector'], 
			['id' => 163, 'name' => 'DVD - Edition Collector Limitée'], 
			['id' => 76, 'name' => 'DVD - Édition Commemorative'], 
			['id' => 5, 'name' => 'DVD - Edition De Luxe'], 
			['id' => 107, 'name' => 'DVD - Edition Définitive'], 
			['id' => 144, 'name' => 'DVD - Edition Digibook'], 
			['id' => 44, 'name' => 'DVD - Edition Digipack'], 
			['id' => 18, 'name' => 'DVD - Edition Double'], 
			['id' => 108, 'name' => 'DVD - Edition Ephémère'], 
			['id' => 25, 'name' => 'DVD - Edition Exclusive'], 
			['id' => 17, 'name' => 'DVD - Edition Extrême'], 
			['id' => 116, 'name' => 'DVD - Edition Finale'], 
			['id' => 124, 'name' => 'DVD - Edition Gold'], 
			['id' => 11, 'name' => 'DVD - Edition Limitée'], 
			['id' => 10, 'name' => 'DVD - Edition Locative'], 
			['id' => 16, 'name' => 'DVD - Edition Numérotée'], 
			['id' => 29, 'name' => 'DVD - Edition Platinum'], 
			['id' => 160, 'name' => 'DVD - Edition Premium'], 
			['id' => 3, 'name' => 'DVD - Edition Prestige'], 
			['id' => 31, 'name' => 'DVD - Edition Remasterisée'], 
			['id' => 60, 'name' => 'DVD - Edition Restaurée'], 
			['id' => 152, 'name' => 'DVD - Edition Simple'], 
			['id' => 4, 'name' => 'DVD - Edition Single'], 
			['id' => 15, 'name' => 'DVD - Edition Spéciale'], 
			['id' => 165, 'name' => 'DVD - Edition Spéciale AMAZON'], 
			['id' => 164, 'name' => 'DVD - Edition Spéciale FNAC'], 
			['id' => 9, 'name' => 'DVD - Edition Standard'], 
			['id' => 123, 'name' => 'DVD - Edition Steelbook'], 
			['id' => 14, 'name' => 'DVD - Edition Triple'], 
			['id' => 26, 'name' => 'DVD - Mid Price'], 
			['id' => 156, 'name' => 'DVD - Mon petit cinéma'], 
			['id' => 13, 'name' => 'DVD - Pack Spécial'], 
			['id' => 19, 'name' => 'DVD - Ultimate Edition'], 
			['id' => 23, 'name' => 'DVD - Version Intégrale'], 
			['id' => 12, 'name' => 'DVD - Version Longue'], 
			['id' => 141, 'name' => 'DVD - WB Environmental'], 
			['id' => 161, 'name' => 'DVD + CD Audio'], 
			['id' => 71, 'name' => 'DVD + Copie Digitale'], 
			['id' => 162, 'name' => 'DVD + Etui baladeur MP3'], 
			['id' => 193, 'name' => 'DVD + Goodies'], 
			['id' => 194, 'name' => 'DVD + Livre'], 
			['id' => 146, 'name' => 'DVD + UMD'], 
			['id' => 185, 'name' => 'DVD-Rom'], 
			['id' => 28, 'name' => 'HD-DVD'], 
			['id' => 130, 'name' => 'HD-DVD - Edition Collector'], 
			['id' => 154, 'name' => 'HD-DVD - Edition Simple'], 
			['id' => 145, 'name' => 'HD-DVD - Edition Spéciale'], 
			['id' => 158, 'name' => 'Pack Duo - Blu-Ray + DVD'],

			['id' => 95, 'name' => 'JEU - 3DS'],
			['id' => 94, 'name' => 'JEU - DS'],
			['id' => 93, 'name' => 'JEU - LCM'],
			['id' => 92, 'name' => 'JEU - PC'],
			['id' => 91, 'name' => 'JEU - PS2'],
			['id' => 88, 'name' => 'JEU - PS3'],
			['id' => 87, 'name' => 'JEU - PSP'],
			['id' => 86, 'name' => 'JEU - PSvita'],
			['id' => 85, 'name' => 'JEU - Wii'],
			['id' => 96, 'name' => 'JEU - Wii U'],
			['id' => 84, 'name' => 'JEU - Xbox 360'],

			['id' => 38, 'name' => 'PDR - Blu-Ray'],
			['id' => 37, 'name' => 'PDR - DVD'], 
			['id' => 36, 'name' => 'PDR - VHS'], 
			['id' => 49, 'name' => 'Superbit'], 
			['id' => 7, 'name' => 'UMD'], 
			['id' => 22, 'name' => 'VHS'], 
			['id' => 191, 'name' => 'VHS - Edition Simple']
		];
	}

	public function all(){
		return $this->data;
	}

	public function getByID($id){
		$data = array_filter($this->data, function($e) use ($id){
			return $id == $e['id'];
		});

		if(empty($data)) return false;

		$data = array_values($data);
		return $data[0];
	}

}